- name: modify repository
  apt_repository:
    repo: 'deb http://dl.bintray.com/rundeck/rundeck-deb /'
    state: present

- name: install
  apt:
    name: "rundeck={{ version }}*"
    state: present
    force: yes

- name: download plugins
  get_url:
    url: "{{ item }}"
    dest: "/var/lib/rundeck/libext/{{ item.split('/')[-1] }}"
    mode: 0644
  with_items: plugins

- name: rundeckd is enabled
  service:
    name: rundeckd
    state: started
    enabled: yes
