- name: modify repository
  apt_repository:
    repo: 'deb http://dl.bintray.com/rundeck/rundeck-deb /'
    state: present

- name: install
  apt:
    name: "rundeck={{ version }}*"
    state: present
    force: yes

- name: download plugins
  get_url:
    url: "https://github.com/rundeck-plugins/{{ item.name }}/releases/download/{{ item.version }}/{{ item.name }}-{{ item.version }}.jar"
    dest: "/var/lib/rundeck/libext/{{ item.name }}-{{ item.version }}.jar"
    mode: 0644
  with_items: plugins

- name: rundeckd is enabled
  service:
    name: rundeckd
    state: started
    enabled: yes
